apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-deploiement
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Proprio
  template:
    metadata:
      labels:
        app: Proprio
    spec:
      containers:
        - name: mon-conteneur
          image: proprio.azurecr.io/proprio:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mon-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: Proprio
